### ISSUE TITLE
Use travis to auto-deploy site

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokehplots.com#6]
Have implemented something similar at https://github.com/bokeh-cookbook/bokeh-cookbook/blob/master/deploy.sh which was copied from the blaze blog.

Pushing to master should redeploy the site.

**Comment by bryevdv** [comment]
Considering shuttering this site, at least in its current form, and pulling everything back into the docs build to make content management simpler, from one place.

**Comment by birdsarah** [comment]
I can't even remember the motivation for making bokehplots.com in the first place - do you?

**Comment by bryevdv** [comment]
To have a splashy, market-y landing site for people looking for very quick, very high level information. But that never really happened, so now it's just an extra thing to maintain.

**Comment by bryevdv** [comment]
Actually anoter idea could be to move this content to `bokeh.github.io`, which allows it to still be separate from "docs" docs, but would be much easier to edit and update.

**Comment by birdsarah** [comment]
I mean there's barely any content. But yeah, the stuff that's still relavent could live on `bokeh.github.io`. It would say on balance if probable just belongs on an about page on `bokeh.pydata.org`.
